### PR TITLE
Adding Spoonflower

### PR DESCRIPTION
**Pull request by walshka**
Contributor: Kelly Walsh, Sr. Director of Engineering Spoonflower, kwalsh@spoonflower.com
Source: internal headcount

Of 16 full-time web developers who regularly deploy code in Ruby on Rails, Javascript, HTML and CSS, 10 are women. This includes the main Spoonflower team (6 women out of 7 developers), Sprout Patterns project (2 women out of 3 developers), Roostery project (1 developer, male) and the international team (3 women out of 5 developers).

### CODE REVIEW

**Comment by triketora** [comment]
Hi! Thanks so much for contributing. Mind fixing the typo in num_eng?

**Comment by walshka** [comment]
That's what I get for getting excited and wanting to contribute late at night. :-) Thanks! Should be fixed now.

**Comment by triketora** [comment]
(Sorry for the slow responses, it's been a bit hectic over here recently...) One more nitpick, can you squash the commits together?

**Comment by walshka** [comment]
(No worries, I've been slow myself, such is life.) I was super lazy and did this change in the github web ui, which after a fair bit of searching does not appear to have a method to squash commits. As I'm several clean commits behind master already, I'll just close this, open a new, and actually pay attention this time.
Sorry for the confusion!

**Pull request closed without merging**
