### PR TITLE
Addressing ambiguous language used to denote full time permanent employees

### PR DESCRIPTION
**Pull request by psykrsna**
As discussed in the Issue #283 : Full-time or permanent employees?

### CODE REVIEW

**Comment by triketora** [comment]
I think "full-time" is still more common in the parlance than "permanent". I'd be okay with doing "full-time, permanent" employees" though.

**Comment by psykrsna** [comment]
I believe full-time as a requirement has already been stated quite clearly in the first line:

> For the purposes of this project, I am counting "female engineers" as women who are writing or architecting software, and are in full-time roles.

Also, I do not like the connotation of the word "permanent employee", can we alternatively use a neutral term like "regular employee"?

> ... Only regular employees please, no part-timers, interns or contractors.

or

> ... Only full-time regular employees please, no interns or contractors.

Let me know.

**Comment by triketora** [comment]
Hm... I'd like a term that people are familiar with and have the right associations with, although of course legally correct terminology is good too. "Regular employee" isn't something I've heard; is it the technical legal parlance?

**Comment by psykrsna** [comment]
I am sorry, I am as uneducated as anybody with respect to legal parlance, but from what I have found on google, "permanent employee" and "regular employee" seem interchangeable. 

Either ways, what do you say to ditching both the prefixes, "permanent" as well as "regular", in favour of only "employee"? I believe it provides sufficient definition. So the line would read:
> Only employees please, no interns or contractors.

Another way of communicating the same message could be:
> Only people from the core team please, no interns or contractors.

**Comment by triketora** [comment]
Right now it says "full-time employees", since interns can also be considered employees. "Core team" seems like it's more ambiguous. What do you think?

**Comment by psykrsna** [comment]
Interns should not be considered as employees, especially once you've explicitly stated "no interns or contractors", though I admit "core team" can be perceived differently depending on the context of the company.

That being said, according to our conversation so far I would finally only recommend removing the "full-time" prefix because:
1. That is what caused the confusion in issue #283 
2. Full time as a requirement has already been stated in the first line and it doesn't make sense repeating it.

**Pull request closed without merging**
